[package]
name = "wasm-lib"
version = "0.1.0"
authors = ["Lee Gyu Cheol <leegyu4dev@gmail.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/lee-gyu/rust-wasm-demo"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
